name: stunting_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_database: ^10.4.0
  intl: ^0.18.1
  flutter_sticky_header: ^0.6.5
  shared_preferences: ^2.3.2
  firebase_auth: ^4.16.0
  device_info_plus: ^10.1.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0
  connectivity_plus: ^7.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.17
  provider: ^6.1.2 # Direkomendasikan untuk state management
  fl_chart: ^0.68.0 # <-- TAMBAHKAN BARIS INI

dev_dependencies:
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  test_api: ^0.7.6
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/Illustrations/
    - assets/icons/
    - assets/edukasi/tab1/
    - assets/edukasi/tab2/ 
    - assets/edukasi/tab3/
    - assets/edukasi/tab4/
    - assets/edukasi/tab5/
    - assets/edukasi/tab6/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/icon_apps.png
  adaptive_icon_background: "#64B5F6"
  adaptive_icon_foreground: assets/icons/icon_apps.png
  remove_alpha_ios: true