// lib/firebase_options.dart - JANGAN EDIT FILE INI SECARA MANUAL!
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      // Jika kamu mengkonfigurasi untuk Windows atau Linux, akan ada juga:
      // case TargetPlatform.windows:
      //   return windows;
      // case TargetPlatform.linux:
      //   return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --- Konstanta FirebaseOptions untuk masing-masing platform ---
  // Perhatikan penamaannya: 'web', 'android', 'ios', bukan 'WebFirebaseOptions'
  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyCqFjCV_9CZmYeIvcK9FVy4drmKUlSaIWY', // Ini akan menjadi kunci API web-mu
    appId: '1:963656261848:web:7219f7fca5fc70afb237ad', // ID aplikasi web-mu
    messagingSenderId: '963656261848',
    projectId: 'situntas-7bbff',
    authDomain: 'situntas-7bbff.firebaseapp.com',
    storageBucket: 'situntas-7bbff.appspot.com',
    measurementId: 'G-DGF0CP099H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyDconZaCQpkxIJ5KQBF-3tEU0rxYsLkIe8', // Ini akan menjadi kunci API Android-mu
    appId:
        '1:963656261848:android:c939ccc86ab2dcdbb237ad', // ID aplikasi Android-mu
    messagingSenderId: '963656261848',
    projectId: 'situntas-7bbff',
    storageBucket: 'situntas-7bbff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyBqLWsqFjYAdGyihKTahMRDQMo0N6NVjAs', // Ini akan menjadi kunci API iOS-mu
    appId: '1:963656261848:ios:d9e01cfe8b675dfcb237ad', // ID aplikasi iOS-mu
    messagingSenderId: '963656261848',
    projectId: 'situntas-7bbff',
    storageBucket: 'situntas-7bbff.appspot.com',
    iosClientId:
        '963656261848-v7r3vq1v6haupv0l1mdrmsf56ktnua60.apps.googleusercontent.com',
    iosBundleId: 'com.example.stuntingapplication', // Bundle ID aplikasi iOS-mu
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyBqLWsqFjYAdGyihKTahMRDQMo0N6NVjAs', // Ini akan menjadi kunci API macOS-mu
    appId: '1:963656261848:ios:d9e01cfe8b675dfcb237ad', // ID aplikasi macOS-mu
    messagingSenderId: '963656261848',
    projectId: 'situntas-7bbff',
    storageBucket: 'situntas-7bbff.appspot.com',
    iosClientId:
        '963656261848-v7r3vq1v6haupv0l1mdrmsf56ktnua60.apps.googleusercontent.com',
    iosBundleId:
        'com.example.stuntingapplication', // Bundle ID aplikasi macOS-mu
  );
  // ... dan seterusnya untuk Windows, Linux
}
