# Nama workflow Anda
name: Build Flutter App

# Pemicu workflow (misalnya saat ada push ke branch main)
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # Menggunakan runner macOS karena kita membangun untuk iOS
    runs-on: macos-latest

    steps:
      # 1. Checkout kode dari repository
      - uses: actions/checkout@v3

      # 2. Setup Java (diperlukan oleh Flutter)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # 3. Setup Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Ambil dependensi awal
      - run: flutter pub get

      # 5. ✨ (LANGKAH BARU) Perbarui dependensi yang usang
      # Ini akan menyelesaikan masalah header non-modular
      - name: Update Flutter Dependencies
        run: flutter pub upgrade --major-versions

      # 6. (OPSIONAL TAPI DISARANKAN) Bersihkan build iOS sebelumnya
      - name: Clean iOS project
        run: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # 7. Jalankan perintah build iOS Anda
      - name: Build iOS Release
        run: flutter build ios --release --no-codesign
