# Nama alur kerja (workflow) yang akan tampil di tab Actions GitHub
name: Build Flutter iOS App

# Menentukan kapan alur kerja ini akan dijalankan
on:
  # Juga memungkinkan alur kerja ini dijalankan secara manual dari tab Actions
  workflow_dispatch:

# Daftar pekerjaan (jobs) yang akan dijalankan dalam alur kerja ini
jobs:
  build:
    # Menentukan nama pekerjaan
    name: Build iOS App
    # Menggunakan runner terbaru dari macOS yang disediakan oleh GitHub
    # Ini diperlukan karena untuk membangun aplikasi iOS, kita butuh Xcode
    runs-on: macos-latest

    # Langkah-langkah (steps) yang akan dieksekusi dalam pekerjaan ini
    steps:
      # Langkah 1: Mengunduh (checkout) kode sumber dari repositori Anda
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Langkah 2: Mengatur environment Java (seringkali dibutuhkan oleh Flutter)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      # Langkah 3: Mengatur SDK Flutter menggunakan action dari komunitas
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          # Anda bisa mengganti versi Flutter sesuai dengan yang Anda gunakan di proyek
          flutter-version: '3.35.5' 
          channel: 'stable'
          cache: true # Mengaktifkan cache untuk mempercepat proses build di masa depan

      # Langkah 4: Menginstal semua dependency proyek Flutter
      - name: Install dependencies
        run: flutter pub get

      # Langkah 5: Menjalankan proses build untuk iOS
      # --release: Membangun versi rilis (production)
      # --no-codesign: Melewatkan proses code signing, karena kita tidak memiliki sertifikat di environment CI
      - name: Build iOS application
        run: flutter build ios --release --no-codesign

      # Langkah 6: Mengunggah artefak hasil build (.app)
      # Hasil build ini nantinya bisa Anda unduh dari halaman ringkasan alur kerja
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          # Nama artefak yang akan diunggah
          name: release-ios-app
          # Path menuju folder hasil build aplikasi iOS
          path: build/ios/iphoneos/*.app