# Nama workflow
name: Build iOS via HashiCorp Vault

on:
  push:
    branches: [ "main" ]

# Izin untuk mendapatkan OIDC token dari GitHub
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # 1. Mengambil secret dari HashiCorp Vault menggunakan OIDC
      - name: Import Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://your-vault-server.com:8200 # <-- Alamat server Vault Anda
          role: my-flutter-app # <-- Nama peran yang dibuat di Vault
          method: jwt
          path: secret/data/flutter-ci # <-- Path tempat secret disimpan
          exportEnv: true # <-- PENTING: Membuat secret tersedia sebagai environment variable

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      # 2. Impor sertifikat & profil menggunakan secret yang sudah diambil dari Vault
      # Perhatikan, kita tidak lagi menggunakan ${{ secrets.* }}
      - name: Import Code Signing Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ env.BUILD_CERTIFICATE_BASE_64 }}
          p12-password: ${{ env.P12_PASSWORD }}

      - name: Import Provisioning Profile
        uses: apple-actions/import-provisioning-profile@v1
        with:
          provisioning-profile-base64: ${{ env.BUILD_PROVISION_PROFILE_BASE_64 }}
      
      - name: Increment Build Number
        run: |
          cd ios
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $(git rev-list --count HEAD)" "Runner/Info.plist"

      - name: Build IPA for iOS
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      # 3. Unggah ke TestFlight menggunakan secret dari Vault
      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v2
        with:
          app-path: "build/ios/ipa/*.ipa"
          issuer-id: ${{ env.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ env.APPSTORE_KEY_ID }}
          api-private-key: ${{ env.APPSTORE_PRIVATE_KEY }}